apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
      on_demand_tls {
        ask {$CADDY_ASK_URL}
        interval 5m
        burst 10
      }
    }

    https:// {
      tls {
        on_demand
      }
      reverse_proxy {$CADDY_UPSTREAM}
    }
